# Even though we run everything inside docker Travis require
# us to pick a language else it will pick Ruby by default
# Choose a lightweight base image; we provide our own build tools.
# https://github.com/lukasmartinelli/hadolint/blob/master/.travis.yml#L1
# language: generic was failing in OSX so in that case you can use language: c
language: generic

# Omit running tests on temporal branches,
#  i.e. branches with names that start with "tmp"
branches:
  except:
    - /^tmp/

env:
  global:
    - TEST_SLEEPS="0.7"
    - ADDED_TEST_SLEEP="6.5"

matrix:
  include:
    # Linux with docker:stable compose:stable
    # Use DOCKER_PUSH_LATEST=false to debug
    - os: linux
      language: generic
      sudo: required
      dist: trusty
      services:
        - docker
      env:
        - DOCKER_VERSION="stable"
          DOCKER_COMPOSE_VERSION="1.14.0"
          DOCKER_PUSH=true
          DOCKER_PUSH_LATEST=true

before_install:
  - travis_retry ./test/before_install_setup
  - travis_retry ./test/before_install_build

install:
  - ./test/install

script:
  - ./test/script_start
  - travis_retry ./test/script_scenario_basic
  - travis_retry ./test/script_scenario_restart
  - travis_retry ./test/script_scenario_node_dies
  - travis_retry ./test/script_scenario_make
  - travis_retry ./test/script_scenario_compose_N_N

# cleanup though doesn't seem to be necessary in Travis infra
after_script:
  - ./test/after_script

after_success:
  - ./test/script_end
